name: tuit_lms
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  dio_cookie_manager: ^3.3.0
  html: ^0.15.6
  json_annotation: ^4.9.0
  native_dio_adapter: ^1.5.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  json_serializable: ^6.11.1
  build_runner: ^2.9.0

